fixtures:
  repositories:
    'inifile':  'git://github.com/puppetlabs/puppetlabs-inifile'
    'keystone': 'git://github.com/stackforge/puppet-keystone.git'
    'mysql':
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: 'origin/0.x'
    'postgresql':
      repo: 'git://github.com/puppetlabs/puppet-postgresql.git'
      ref: '2.5.0'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    'trove': "#{source_dir}"
