name         'puppetlabs-trove'
version      '4.0.0'
author       'eNovance and StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Trove'
description  'Installs and configures OpenStack Trove (Database service).'
project_page 'https://launchpad.net/puppet-trove'
source       'https://github.com/stackforge/puppet-trove'

dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/keystone', '>=4.0.0 <5.0.0'
dependency 'puppetlabs/stdlib', '>=3.2.0'
dependency 'stackforge/openstacklib', '>=5.0.0'
